# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-30 18:24
from __future__ import unicode_literals

import coursereg.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('user_type', models.IntegerField(choices=[(0, 'Student'), (1, 'Faculty'), (2, 'DCC'), (3, 'Other')], default=3)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('sr_no', models.CharField(default='-', max_length=200)),
                ('telephone', models.CharField(blank=True, default='', max_length=100)),
                ('is_dcc_review_pending', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('term', models.IntegerField(choices=[(0, 'Aug-Dec'), (1, 'Jan-Apr'), (2, 'Summer'), (3, 'Other')], default=coursereg.models.get_recent_term)),
                ('year', models.CharField(default=coursereg.models.get_recent_year, max_length=4)),
                ('num_credits', models.IntegerField(default=3, verbose_name='Number of credits')),
                ('credit_label', models.CharField(blank=True, default='', max_length=100, verbose_name='Credit split (ex: 3:0)')),
                ('should_count_towards_cgpa', models.BooleanField(default=True)),
                ('auto_instructor_approve', models.BooleanField(default=False)),
                ('last_reg_date', models.DateTimeField(default=coursereg.models.get_recent_last_reg_date, verbose_name='Last registration date')),
                ('last_conversion_date', models.DateTimeField(default=coursereg.models.get_recent_last_conversion_date, verbose_name='Last credit/audit conversion date')),
                ('last_drop_date', models.DateTimeField(default=coursereg.models.get_recent_last_drop_date, verbose_name='Last drop date')),
                ('last_drop_with_mention_date', models.DateTimeField(default=coursereg.models.get_recent_last_drop_with_mention_date, verbose_name='Last drop with mention date')),
                ('last_grade_date', models.DateTimeField(default=coursereg.models.get_recent_last_grade_date, verbose_name='Last grade date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(default='-', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_for', models.IntegerField(choices=[(0, 'Student'), (1, 'Faculty'), (2, 'DCC')], default=0)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=10)),
                ('should_count_towards_cgpa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.IntegerField(choices=[(0, 'Adviser'), (1, 'Instructor'), (2, 'DCC'), (3, 'Other')], default=2)),
                ('message', models.TextField()),
                ('is_student_acknowledged', models.BooleanField(default=False)),
                ('is_adviser_acknowledged', models.BooleanField(default=False)),
                ('is_dcc_acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.IntegerField(choices=[(0, 'Student'), (1, 'Instructor'), (2, 'TA')], default=1)),
                ('is_credit', models.BooleanField(default=True)),
                ('is_drop', models.BooleanField(default=False)),
                ('is_drop_mentioned', models.BooleanField(default=False)),
                ('is_adviser_approved', models.BooleanField(default=False)),
                ('is_instructor_approved', models.BooleanField(default=False)),
                ('should_count_towards_cgpa', models.BooleanField(default=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereg.Course')),
                ('grade', models.ForeignKey(blank=True, default=coursereg.models.get_default_grade, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursereg.Grade')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereg.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coursereg.Degree'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursereg.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
