# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 06:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=250)),
                ('user_type', models.IntegerField(choices=[(0, 'Faculty'), (1, 'Student'), (2, 'Other'), (3, 'DCC')], default=1)),
                ('program', models.IntegerField(choices=[(0, 'Other'), (1, 'MTech'), (2, 'MSc'), (3, 'PhD'), (4, 'ME')], default=0)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('sr_no', models.CharField(default='-', max_length=200)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('adviser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('term', models.IntegerField(choices=[(0, 'Aug-Dec'), (1, 'Jan-Apr'), (2, 'Summer'), (3, 'Other')], default=0)),
                ('last_reg_date', models.DateField(default=django.utils.timezone.now, verbose_name='Last Registration Date')),
                ('credits', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_for', models.IntegerField(choices=[(0, 'Student'), (1, 'Faculty'), (2, 'DCC')], default=0)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_type', models.IntegerField(choices=[(0, 'Credit'), (1, 'Audit'), (2, 'Instructor'), (3, 'TA')], default=2)),
                ('state', models.IntegerField(choices=[(0, 'Requested'), (1, 'Advisor approved'), (2, 'Instructor approved'), (3, 'DCC approved'), (4, 'N/A'), (5, 'Advisor rejected'), (6, 'Instructor rejected'), (7, 'Drop Requested'), (8, 'Advisor approved drop'), (9, 'Advisor rejected drop'), (10, 'DCC disapproved'), (11, 'DCC drop approved'), (12, 'DCC drop rejected'), (13, 'Cancel requested'), (14, 'Advisor approved cancellation'), (15, 'Advisor rejected cancellation'), (16, 'Audit conversion requested'), (17, 'Advisor approved audit conversion'), (18, 'Advisor rejected audit conversion'), (19, 'DCC approved audit conversion'), (20, 'DCC rejected audit conversion'), (21, 'Credit conversion requested'), (22, 'Advisor approved credit conversion'), (23, 'Advisor rejects credit conversion'), (24, 'DCC approved credit conversion'), (25, 'DCC rejected credit conversion')], default=4)),
                ('grade', models.IntegerField(choices=[(0, 'N/A'), (1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'F')], default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereg.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereg.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coursereg.Department'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
