# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-31 07:03
from __future__ import unicode_literals

import coursereg.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereg', '0003_auto_20160731_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='last_conversion_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_conversion_date, verbose_name='Last credit/audit conversion date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_drop_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_drop_date, verbose_name='Last drop date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_drop_with_mention_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_drop_with_mention_date, verbose_name='Last drop with mention date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_grade_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_grade_date, verbose_name='Last grade date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_reg_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_reg_date, verbose_name='Last registration date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.IntegerField(choices=[(0, 'Aug-Dec'), (1, 'Jan-Apr'), (2, 'Summer'), (3, 'Other')], default=coursereg.models.get_recent_term),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(default=coursereg.models.get_recent_year, max_length=4),
        ),
    ]
