# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 15:57
from __future__ import unicode_literals

import coursereg.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursereg', '0004_auto_20160731_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='state',
        ),
        migrations.AlterField(
            model_name='course',
            name='last_conversion_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_conversion_date, verbose_name='Last credit/audit conversion date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_drop_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_drop_date, verbose_name='Last drop date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_drop_with_mention_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_drop_with_mention_date, verbose_name='Last drop with mention date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_grade_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_grade_date, verbose_name='Last grade date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='last_reg_date',
            field=models.DateTimeField(default=coursereg.models.get_recent_last_reg_date, verbose_name='Last registration date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.CharField(default=coursereg.models.get_recent_year, max_length=4),
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='new_grade',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='participant',
            name='grade',
            field=models.ForeignKey(blank=True, default=coursereg.models.get_default_grade, on_delete=django.db.models.deletion.CASCADE, to='coursereg.Grade'),
        ),
        migrations.RenameField(
            model_name='course',
            old_name='new_term',
            new_name='term',
        ),
        migrations.AlterField(
            model_name='course',
            name='term',
            field=models.ForeignKey(default=coursereg.models.get_recent_term, on_delete=django.db.models.deletion.CASCADE, to='coursereg.Term'),
        ),
    ]
