# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-31 15:57
from __future__ import unicode_literals

import coursereg.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coursereg', '0004_auto_20160731_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='course',
            name='term',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_reg_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_drop_date',
        ),
        migrations.AlterField(
            model_name='course',
            name='new_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coursereg.Term'),
        ),
        migrations.RenameField(
            model_name='course',
            old_name='new_term',
            new_name='term',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='new_credits',
            new_name='credits',
        ),

        migrations.RemoveField(
            model_name='participant',
            name='state',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_adviser_approved',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='is_instructor_approved',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='grade',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='new_grade',
            new_name='grade',
        ),
        migrations.AlterField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='origin',
            field=models.IntegerField(choices=[(0, 'Adviser'), (1, 'Instructor'), (2, 'DCC'), (3, 'Other'), (4, 'Student')], default=2),
        ),

    ]
