# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereg', '0005_auto_20160731_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dcc_approved_registration',
            field=models.BooleanField(default=False),
        ),
    ]
