# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereg', '0006_user_is_dcc_approved_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dcc_sent_notification',
            field=models.BooleanField(default=False),
        ),
    ]
