# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-07 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coursereg', '0007_user_is_dcc_sent_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='lock_from_student',
            field=models.BooleanField(default=False),
        ),
    ]
